<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>

<groupId>com.example</groupId> <!-- Le groupe ou l'organisation -->
<artifactId>ImageApp</artifactId> <!-- Nom du projet -->
<version>1.0</version> <!-- Version du projet -->

<name>My Project</name> <!-- Nom descriptif du projet -->
<description>Un projet Maven exemple.</description> <!-- Description -->

<dependencies>
    <!-- Dépendances Maven -->
</dependencies>

<build>
<sourceDirectory>src/application</sourceDirectory>
<plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-shade-plugin</artifactId>
      <version>3.2.4</version>
      <executions>
        <execution>
          <phase>package</phase>
          <goals>
            <goal>shade</goal>
          </goals>
          <configuration>
            <createDependencyReducedPom>false</createDependencyReducedPom>
            <transformers>
              <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                <mainClass>application.Main</mainClass> <!-- Changez cela selon votre classe principale -->
              </transformer>
            </transformers>
          </configuration>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
</project>